jaffle_shop:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server' # (The ODBC Driver installed on your system)
      server: "localhost"
      schema: "dbt"
      port: 1433
      database: "msdb"
      user: "sa"
      password: "L0calTesting!"
